printSite/printSite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.defaults import page_not_found
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('justsite.urls')),
    path('users/', include('users.urls', namespace="users")),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = page_not_found

admin.site.site_header = "Панель администрирования"

admin.site.index_title = "Товары, товарчики"

printSite/users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, PasswordChangeDoneView
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),

    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name="users/password_change_done.html"), name="password_change_done"),
]

printSite/users/models.py
from django.contrib.auth import get_user_model
from django.contrib.auth.models import AbstractUser
from django.db import models
from justsite.models import Items




class User(AbstractUser):
    cart = models.ManyToManyField(Items, blank=True, related_name='cart', verbose_name="Корзина", through="Cart")
    phone_num = models.CharField(max_length=12, verbose_name="Номер телефона", blank=True, null=True)



class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart_users', db_constraint=False)
    item = models.ForeignKey(Items, on_delete=models.CASCADE, related_name='cart_items', db_constraint=False)

printSite/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
import re


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    error_messages = {
        'invalid_login': "Неверный E-mail или пароль. Пожалуйста, попробуйте снова."
    }

    class Meta:
        model = get_user_model()
        fields = ['username', 'password']


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    password2 = forms.CharField(label='Повтор пароля', widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    phone_num = forms.CharField(label='Номер телефона', widget=forms.TextInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'phone_num', 'password1', 'password2']
        labels = {
            'email': 'E-mail',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-input'}),
        }

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        model = get_user_model()
        if model.objects.filter(email=email).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        model = get_user_model()
        if model.objects.filter(username=username).exists():
            raise forms.ValidationError("Пользователь с таким именем уже зарегистрирован!")
        return username

    def clean_phone_num(self):
        phone_num = self.cleaned_data['phone_num']
        if not re.match(r'^(\+7|8)\d{10}$', phone_num):
            raise forms.ValidationError(
                "Введите номер телефона в формате +75556667799 или 85556667799"
            )
        return phone_num



class ProfileUserForm(forms.ModelForm):
    username = forms.CharField(label='Логин', widget=forms.TextInput(attrs={'class': 'form-input'}))
    email = forms.CharField(label='E-mail', widget=forms.TextInput(attrs={'class': 'form-input'}))
    phone_num = forms.CharField(label='Номер телефона', widget=forms.TextInput(attrs={'class': 'form-input'}))

    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super(ProfileUserForm, self).__init__(*args, **kwargs)

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        model = get_user_model()
        if model.objects.filter(email=email).exclude(pk=self.user.pk).exists():
            raise forms.ValidationError("Такой E-mail уже существует!")
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        model = get_user_model()
        if model.objects.filter(username=username).exclude(pk=self.user.pk).exists():
            raise forms.ValidationError("Пользователь с таким именем уже зарегистрирован!")
        return username

    def clean_phone_num(self):
        phone_num = self.cleaned_data['phone_num']
        if not re.match(r'^(\+7|8)\d{10}$', phone_num):
            raise forms.ValidationError(
                "Введите номер телефона в формате +75556667799 или 85556667799"
            )
        return phone_num

    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'phone_num']
        labels = {
            'username': 'Логин',
            'email': 'E-mail',
            'phone_num': 'Номер телефона',
        }




class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль", widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля", widget=forms.PasswordInput(attrs={'class': 'form-input'}))

printSite/users/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, UpdateView

from users.forms import LoginUserForm, RegisterUserForm, ProfileUserForm, UserPasswordChangeForm


class LoginUser(LoginView):
    form_class = LoginUserForm
    template_name = 'users/login.html'
    extra_context = {'title': "Авторизация"}


    def get_context_data(self, **kwargs):

        context = super().get_context_data(**kwargs)
        return context



def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('users:login'))



class RegisterUser(CreateView):
    form_class = RegisterUserForm
    template_name = 'users/register.html'
    extra_context = {'title': "Регистрация"}

    success_url = reverse_lazy('users:login')




class ProfileUser(LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = ProfileUserForm
    template_name = 'users/profile.html'
    extra_context = {'title': "Профиль пользователя"}

    def get_success_url(self):
        return reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        messages.success(self.request, "Ваш профиль успешно обновлен!")
        return super().form_valid(form)




class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy("users:password_change_done")
    template_name = "users/password_change_form.html"
    extra_context = {'title': "Изменение пароля"}

printSite/users/templates/users/login.html
{% extends 'base.html' %}
 
{% block content %}
<h1>{{ title }}</h1>

{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class="message {{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div>{{ form.non_field_errors }}</div>
    {% for f in form %}
    <div><label for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</div>
    <div>{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Войти</button></p>
</form>
 
{% endblock %}

printSite/users/templates/users/password_change_done.html
{% extends 'base.html' %}
 
{% block content %}
<h1>Пароль успешно изменен!</h1>
 
<p >Вы успешно изменили пароль. <a href="{% url 'users:profile' %}">Вернуться в профиль.</a></p>
{% endblock %}

printSite/users/templates/users/password_change_form.html
{% extends 'base.html' %}
 
{% block content %}
<h1>{{ title }}</h1>



<form method="post">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <div><label class="form-label" for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</div>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p ><button type="submit">Изменить пароль</button></p>
</form>
 
{% endblock %}

printSite/users/templates/users/profile.html
{% extends 'base.html' %}
 
{% block content %}
<h1>{{ title }}</h1>





{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class="message {{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}


<form method="post">
    {% csrf_token %}
    <div>{{ form.non_field_errors }}</div>
    {% for field in form %}
    <div><label for="{{ field.id_for_label }}">{{field.label}}: </label>{{ field }}</div>
    <div class="form-error">{{ field.errors }}</div>
    {% endfor %}
    <p ><button type="submit">Сохранить</button></p>
</form>
<div><a href="{% url 'users:password_change' %}">Сменить пароль</a></div>
<div><a href="{% url 'users:logout' %}">Выйти</a></div>

{% endblock %}

printSite/users/templates/users/register.html
{% extends 'base.html' %}
 
{% block content %}
<h1>{{ title }}</h1>

{% if messages %}
<div class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class="message {{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
</div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}" />
    <div>{{ form.non_field_errors }}</div>
    {% for f in form %}
    <div><label for="{{ f.id_for_label }}">{{f.label}}: </label>{{ f }}</div>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p ><button type="submit">Регистрация</button></p>
</form>
 
{% endblock %}